# Generated by Django 3.2.11 on 2022-06-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartlist_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='product',
            new_name='cproduct',
        ),
        migrations.RenameField(
            model_name='cartlist',
            old_name='user',
            new_name='cuser',
        ),
    ]
