# Generated by Django 3.2.11 on 2022-06-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartlist_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='status',
            field=models.CharField(choices=[('p1', 'Development Under P1'), ('p2', 'Development Under P2'), ('p3', 'Development Under P3'), ('p4', 'Development Under P4'), ('p5', 'Development Under P5'), ('reject', 'Rejected'), ('final', 'Finalised')], default='p1', max_length=100),
        ),
    ]
