# Generated by Django 3.2.11 on 2022-06-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
