# Generated by Django 3.2.11 on 2022-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartlist_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='tilldate',
            field=models.IntegerField(default=0),
        ),
    ]
