# Generated by Django 3.2.11 on 2022-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmens',
            name='category',
            field=models.CharField(choices=[('casual', 'CASUAL'), ('formal', 'FORMAL'), ('semi-formal', 'SEMI-FORMAL')], default='casual', max_length=20),
        ),
    ]
