# Generated by Django 3.2.11 on 2022-04-21 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0003_tmens_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmens',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
