# Generated by Django 3.2.11 on 2022-04-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0005_ratingreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingreview',
            old_name='users',
            new_name='user',
        ),
    ]
