# Generated by Django 3.2.11 on 2022-04-25 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0006_rename_users_ratingreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmens',
            name='rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
