# Generated by Django 3.2.11 on 2022-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0007_alter_tmens_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmens',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
