# Generated by Django 3.2.11 on 2022-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensapp', '0009_tmens_cartflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmens',
            name='designedby',
            field=models.CharField(choices=[('Anas NS', 'ANAS'), ('Sajith VP', 'SAJITH'), ('Diljith K', 'DILJITH')], default='Anas NS', max_length=20),
        ),
    ]
